#!/bin/bash
set -ouex pipefail

# Initial update
apt update -y

# Required repositories & supporting packages
apt install -y \
  curl \
  gpg \
  lsb-release

curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
install -o root -g root -m 644 microsoft.gpg /usr/share/keyrings
rm microsoft.gpg

echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/ubuntu/$(lsb_release -rs)/prod $(lsb_release -cs) main" > /etc/apt/sources.list.d/microsoft-ubuntu-$(lsb_release -cs)-prod.list
apt update -y

# Remove no longer needed packages
apt remove -y \
  curl \
  gpg \
  lsb-release
apt autoremove -y

# Required packages
apt install -y \
  unattended-upgrades \
  microsoft-identity-broker \
  pipewire-audio-client-libraries

# Intune needs fixes to install properly
# Install its dependencies first
apt-get install -y --no-install-recommends \
    $(apt-cache depends intune-portal | awk '/Depends:/{print $2}')

# Download and extract the Intune package
apt download intune-portal
mv intune-portal_*.deb /tmp/
dpkg-deb -R /tmp/intune-portal_*.deb /tmp/intune-unpacked/

# Remove the postinst step that causes it to break when installing inside the container
sed -i '/systemctl restart polkit\.service 2>\/dev\/null/d' /tmp/intune-unpacked/DEBIAN/postinst
dpkg-deb -b /tmp/intune-unpacked/ /tmp/intune-portal-fixed.deb

# Install patched Intune
dpkg -i /tmp/intune-portal-fixed.deb

# Update password requirements
sed -i '/pam_pwquality\.so/c\password requisite         pam_pwquality.so retry=3 dcredit=-1 ocredit=-1 ucredit=-1 lcredit=-1 minlen=12' /etc/pam.d/common-password
pam-auth-update --force

# Enable automatic updates for more than security patches
sed -i 's|^//[[:space:]]*"\${distro_id}:\${distro_codename}-updates";|"${distro_id}:${distro_codename}-updates";|' /etc/apt/apt.conf.d/50unattended-upgrades
sed -i '/^};/i\    "microsoft-${distro_id}-${distro_codename}-prod:${distro_codename}";' /etc/apt/apt.conf.d/50unattended-upgrades
